### ISSUE TITLE
Issue after install

### ISSUE THREAD

**Issue by luca-ferrari-roma** [markusvankempen/node-red-contrib-lorawan-packet-decrypt-nwkey-appkey#1]
Good morning Markus.
Using your Example node I received this error:

15 Mar 09:23:07 - [info] Installing module: node-red-contrib-lorawan-packet-decrypt-nwkey-appkey, version: 1.0.4
15 Mar 09:23:11 - [info] Installed module: node-red-contrib-lorawan-packet-decrypt-nwkey-appkey
15 Mar 09:23:11 - [info] Added node types:
15 Mar 09:23:11 - [info]  - node-red-contrib-lorawan-packet-decrypt-nwkey-appkey:lorawan-packet-decrypt-nwkey-appkey : Error: Cannot find module './lora-packet'
Require stack:
- C:\Users\ferrluca\.node-red\node_modules\node-red-contrib-lorawan-packet-decrypt-nwkey-appkey\lorawan-packet-decrypt-nwkey-appkey\lorawan-packet-decrypt-nwkey-appkey.js
- C:\Users\ferrluca\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\registry\lib\loader.js
- C:\Users\ferrluca\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\registry\lib\index.js
- C:\Users\ferrluca\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\index.js
- C:\Users\ferrluca\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\index.js
- C:\Users\ferrluca\AppData\Roaming\npm\node_modules\node-red\lib\red.js
- C:\Users\ferrluca\AppData\Roaming\npm\node_modules\node-red\red.js
15 Mar 09:24:04 - [info] Stopping flows
15 Mar 09:24:04 - [info] [udp in:c5aef283.8887f] udp listener stopped
15 Mar 09:24:04 - [info] Stopped flows
15 Mar 09:24:04 - [info] Waiting for missing types to be registered:
15 Mar 09:24:04 - [info]  - lorawan-packet-decrypt-nwkey-appkey

![image](https://user-images.githubusercontent.com/39159409/111124677-0ebd0780-8571-11eb-931d-6d0ba9e31a1e.png)

Ideas?
Thank you

**Comment by markusvankempen** [comment]
Hello Luca

Thank you for testing. I updated the path in github but not on the npm version e.g.
var lora_packet = require('lora-packet');
version 1.0.8 should work ... 
https://flows.nodered.org/node/node-red-contrib-lorawan-packet-decrypt-nwkey-appkey
let me know ... cheers

**Comment by markusvankempen** [comment]
Hello Luca

I fixed it try v1.0.9

Let me know how it goes

Cheers

**Comment by luca-ferrari-roma** [comment]
Thank you Markus.
I have now managed to install the node.
